version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            - run: scp -o StrictHostKeyChecking=no -r ./index.html ubuntu@78.141.222.65://var//www//html/

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
